[production]
prod-app-01 ansible_host=192.168.10.20
prod-app-02 ansible_host=192.168.10.21

[databases]
prod-db-01  ansible_host=192.168.10.30

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
